# Generated by Django 3.1.5 on 2021-01-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30)),
                ('Sobrenome', models.CharField(max_length=80)),
            ],
        ),
    ]
