# Generated by Django 3.1.5 on 2021-01-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producao', '0002_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.DateField(null=True)),
                ('Auto', models.FloatField(null=True)),
                ('RE', models.FloatField(null=True)),
                ('Residencial', models.FloatField(null=True)),
                ('PreFormatado', models.FloatField(null=True)),
                ('Saúde_PJ', models.FloatField(null=True)),
                ('Dental_PF', models.FloatField(null=True)),
                ('Dental_PJ', models.FloatField(null=True)),
                ('Vida_Anual', models.FloatField(null=True)),
                ('Vida_Único', models.FloatField(null=True)),
                ('Vida_Mensal', models.FloatField(null=True)),
                ('Cartão', models.FloatField(null=True)),
                ('Portabilidade', models.FloatField(null=True)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producao.pessoa')),
            ],
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
