# Generated by Django 3.1.5 on 2021-01-29 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producao', '0003_auto_20210129_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producao',
            old_name='PreFormatado',
            new_name='Pré_Formatado',
        ),
    ]
